# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
pool:
  vmImage: 'Ubuntu-16.04'
  
steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '8.x'

- script: npm install

- script: npm run build

- script: npm run package

- task: PublishBuildArtifacts@1
